/* Schema for Postgres DB */

CREATE DATABASE IF NOT EXISTS review_data;

USE review_data;

CREATE TABLE reviews(
  REVIEW_ID INT NOT NULL,
  PRODUCT_ID INT NOT NULL,
  RATING INT NOT NULL,
  SUMMARY VARCHAR(60) NOT NULL,
  RECOMMEND BOOLEAN NOT NULL,
  RESPONSE VARCHAR(1000) DEFAULT NULL,
  BODY VARCHAR(1000) NOT NULL,
  REVIEW_DATE DATE NOT NULL,
  REVIEWER_NAME VARCHAR(60) NOT NULL,
  HELPFULNESS INT DEFAULT 0,
  EMAIL VARCHAR(60) NOT NULL,
  PHOTOS BOOLEAN NOT NULL,
  REPORTED BOOLEAN DEFAULT 0,
  PRIMARY KEY (REVIEW_ID)
);

CREATE TABLE characteristics(
  ID INT NOT NULL,
  ID_NAME VARCHAR(7)
);

CREATE TABLE review_characteristics(
  REVIEW_ID INT NOT NULL,
  CHAR_ID INT NOT NULL,
  CHAR_RATING INT NOT NULL,
  FOREIGN KEY (REVIEW_ID) REFERENCES reviews(REVIEW_ID),
  FOREIGN KEY (CHAR_ID) REFERENCES characteristics(ID)
);
